name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install test dependencies
        run: pip install pytest pandas scikit-learn wandb fastapi psycopg pydantic joblib numpy httpx2 seaborn matplotlib streamlit

      - name: Run Phase 1 tests
        run: pytest "phase 1/cleaning/test_cleaning.py" "phase 1/training/test_train.py"

      - name: Run Phase 2 tests
        run: pytest "phase 2/test_app.py"

      - name: Run Phase 3 tests
        run: pytest "phase 3/test_frontend.py"