name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      WANDB_API_KEY: "${{ secrets.WANDB_API_KEY }}"

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install test dependencies
        run: pip install pytest pandas scikit-learn wandb fastapi psycopg pydantic joblib numpy httpx2 seaborn matplotlib streamlit flake8

      - name: Run Flake8
        run: |
          flake8 \
            --ignore=E501,W291,W293,W292,W391,E302,E305,E303,E128 \
            --ignore=E225,E221,E231,E266,E265,E701,E116,E122,E711,E203 \
            --ignore=F401,F841

      - name: Run Phase 1 tests
        run: pytest "phase 1/cleaning/test_cleaning.py" "phase 1/training/test_train.py"

      - name: Run Phase 2 tests
        run: pytest "phase 2/test_app.py"

      - name: Run Phase 3 tests
        run: pytest "phase 3/test_frontend.py"